### ISSUE TITLE
Changes in Prescriptive Add

### ISSUE THREAD

**Issue by rajesh-danphe** [dprescriptivemaintenance40/DPMCore#24]
a)change in Numbering of FMEA     and FCA according to Failure Mode
 b) Hide child of FMEA an FCA and to Add button on Tree and display tree below with Scroll Feature
 c) Pattern Chart on popup for FCA (Dynamic)

**Comment by shivanni** [comment]
All a, b, c  changes are done

**Comment by rajesh-danphe** [comment]
Closing
